apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: test-cluster
  region: us-east-2
 
vpc:
  id: "vpc-49338d22"  # (optional, must match VPC ID used for each subnet below)
  cidr: "172.31.0.0/16"       # (optional, must match CIDR used by the given VPC)
  subnets:
    public:
      us-east-2c:
        id: "subnet-c88acd84"
        cidr: "172.31.32.0/20" # (optional, must match CIDR used by the given subnet)

      us-east-2a:
        id: "subnet-5b10b630"
        cidr: "172.31.0.0/20"  # (optional, must match CIDR used by the given subnet)

      us-east-2b:
        id: "subnet-93736ce9"
        cidr: "172.31.16.0/20"
iam:
  serviceRoleARN: "arn:aws:iam::705545652606:role/eksClusterRole"

nodeGroups:
  - name: ng-1
    instanceType: t2.micro
    desiredCapacity: 10
    ssh: # import inline public key
      publicKeyPath: /home/ubuntu/.ssh/id_rsa.pub
